# 공통설정
spring:
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB

  application:
    name: withbooks




fileupload:
  contextPath: /home/withbooks/webapps/image/
  