name: Build and deploy JAR app to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: directory change
        run: echo "changed directory"

      - name: 권한변경
        run: echo "권한변경됨"

        
      
